"""update macro tables standardize columns and fix view date column

Revision ID: 325ae849c379
Revises: c24e71c09ba3
Create Date: 2026-06-02 11:38:04.320885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '325ae849c379'
down_revision: Union[str, None] = 'c24e71c09ba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. DROP la table existante (sera remplacée par une vue)
    op.execute("DROP TABLE IF EXISTS v_macro_indicators_daily_v1")
    
    # 2. Restructurer les tables macro
    op.add_column('t_macro_bce_inflation', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('t_macro_bce_inflation', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('t_macro_bce_inflation', sa.Column('value', sa.Float(), nullable=True))
    op.add_column('t_macro_bce_inflation', sa.Column('obs_status', sa.String(length=10), nullable=True))
    op.add_column('t_macro_bce_inflation', sa.Column('time_period', sa.String(length=20), nullable=True))
    op.add_column('t_macro_bce_inflation', sa.Column('indicator_name', sa.String(length=200), nullable=True))
    op.add_column('t_macro_bce_inflation', sa.Column('source_label', sa.String(length=200), nullable=True))
    op.drop_constraint(op.f('t_macro_bce_inflation_date_inflation_key'), 't_macro_bce_inflation', type_='unique')
    op.create_unique_constraint('uq_t_macro_bce_inflation_date', 't_macro_bce_inflation', ['date'])
    op.drop_column('t_macro_bce_inflation', 'date_inflation')
    op.drop_column('t_macro_bce_inflation', 'indicator_name_inflation')
    op.drop_column('t_macro_bce_inflation', 'source_label_inflation')
    op.drop_column('t_macro_bce_inflation', 'time_periode_inflation')
    op.drop_column('t_macro_bce_inflation', 'id_inflation')
    op.drop_column('t_macro_bce_inflation', 'inflation_rate')
    
    op.add_column('t_macro_bce_monetary_m3', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('t_macro_bce_monetary_m3', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('t_macro_bce_monetary_m3', sa.Column('value', sa.Float(), nullable=True))
    op.add_column('t_macro_bce_monetary_m3', sa.Column('obs_status', sa.String(length=10), nullable=True))
    op.add_column('t_macro_bce_monetary_m3', sa.Column('time_period', sa.String(length=20), nullable=True))
    op.add_column('t_macro_bce_monetary_m3', sa.Column('indicator_name', sa.String(length=200), nullable=True))
    op.add_column('t_macro_bce_monetary_m3', sa.Column('source_label', sa.String(length=200), nullable=True))
    op.drop_constraint(op.f('t_macro_bce_monetary_m3_date_monetary_m3_key'), 't_macro_bce_monetary_m3', type_='unique')
    op.create_unique_constraint('uq_t_macro_bce_monetary_m3_date', 't_macro_bce_monetary_m3', ['date'])
    op.drop_column('t_macro_bce_monetary_m3', 'date_monetary_m3')
    op.drop_column('t_macro_bce_monetary_m3', 'monetary_m3_rate')
    op.drop_column('t_macro_bce_monetary_m3', 'source_label_m3')
    op.drop_column('t_macro_bce_monetary_m3', 'indicator_name_m3')
    op.drop_column('t_macro_bce_monetary_m3', 'id_monetary_m3')
    
    op.add_column('t_macro_bce_mro', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('t_macro_bce_mro', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('t_macro_bce_mro', sa.Column('value', sa.Float(), nullable=True))
    op.add_column('t_macro_bce_mro', sa.Column('obs_status', sa.String(length=10), nullable=True))
    op.add_column('t_macro_bce_mro', sa.Column('time_period', sa.String(length=20), nullable=True))
    op.add_column('t_macro_bce_mro', sa.Column('indicator_name', sa.String(length=200), nullable=True))
    op.add_column('t_macro_bce_mro', sa.Column('source_label', sa.String(length=200), nullable=True))
    op.drop_constraint(op.f('t_macro_bce_mro_date_mro_key'), 't_macro_bce_mro', type_='unique')
    op.create_unique_constraint('uq_t_macro_bce_mro_date', 't_macro_bce_mro', ['date'])
    op.drop_column('t_macro_bce_mro', 'date_mro')
    op.drop_column('t_macro_bce_mro', 'source_label_mro')
    op.drop_column('t_macro_bce_mro', 'indicator_name_mro')
    op.drop_column('t_macro_bce_mro', 'rate_mro')
    op.drop_column('t_macro_bce_mro', 'time_periode_mro')
    op.drop_column('t_macro_bce_mro', 'id_mro')
    
    op.add_column('t_macro_bce_unemployment', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('t_macro_bce_unemployment', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('t_macro_bce_unemployment', sa.Column('value', sa.Float(), nullable=True))
    op.add_column('t_macro_bce_unemployment', sa.Column('obs_status', sa.String(length=10), nullable=True))
    op.add_column('t_macro_bce_unemployment', sa.Column('time_period', sa.String(length=20), nullable=True))
    op.add_column('t_macro_bce_unemployment', sa.Column('indicator_name', sa.String(length=200), nullable=True))
    op.add_column('t_macro_bce_unemployment', sa.Column('source_label', sa.String(length=200), nullable=True))
    op.drop_constraint(op.f('t_macro_bce_unemployment_date_unemployment_key'), 't_macro_bce_unemployment', type_='unique')
    op.create_unique_constraint('uq_t_macro_bce_unemployment_date', 't_macro_bce_unemployment', ['date'])
    op.drop_column('t_macro_bce_unemployment', 'source_label_unemployment')
    op.drop_column('t_macro_bce_unemployment', 'date_unemployment')
    op.drop_column('t_macro_bce_unemployment', 'indicator_name_unemployment')
    op.drop_column('t_macro_bce_unemployment', 'id_unemployment')
    op.drop_column('t_macro_bce_unemployment', 'unemployment_rate')
    
    # 3. Recréer la vue avec les nouveaux noms de colonnes et jointure par mois pour propager les valeurs mensuelles
    # Filtrer à partir de 2010-07-14 pour cohérence avec les données Bitcoin
    op.execute("""
        CREATE VIEW v_macro_indicators_daily_v1 AS
        SELECT 
            COALESCE(mro.date, inf.date, unemp.date, m3.date) AS date,
            mro.value AS rate_mro,
            inf.value AS inflation_rate,
            unemp.value AS unemployment_rate,
            m3.value AS monetary_m3_rate
        FROM t_macro_bce_mro mro
        FULL OUTER JOIN t_macro_bce_inflation inf 
            ON DATE_TRUNC('month', mro.date) = DATE_TRUNC('month', inf.date)
        FULL OUTER JOIN t_macro_bce_unemployment unemp 
            ON DATE_TRUNC('month', COALESCE(mro.date, inf.date)) = DATE_TRUNC('month', unemp.date)
        FULL OUTER JOIN t_macro_bce_monetary_m3 m3 
            ON DATE_TRUNC('month', COALESCE(mro.date, inf.date, unemp.date)) = DATE_TRUNC('month', m3.date)
        WHERE COALESCE(mro.date, inf.date, unemp.date, m3.date) >= '2010-07-14'
        ORDER BY date
    """)
    # ### end Alembic commands ###


# ...existing code...

def downgrade() -> None:
    """Downgrade schema - Inverse exact de upgrade()."""
    # 1. Drop la vue
    op.execute("DROP VIEW IF EXISTS v_macro_indicators_daily_v1")

    # 2. Restaurer anciennes colonnes tables macro (INVERSE de upgrade)
    
    # t_macro_bce_inflation - SUPPRIMER nouvelles colonnes, RESTAURER anciennes
    op.add_column('t_macro_bce_inflation', sa.Column('inflation_rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('t_macro_bce_inflation', sa.Column('id_inflation', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('t_macro_bce_inflation', sa.Column('time_periode_inflation', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('t_macro_bce_inflation', sa.Column('source_label_inflation', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('t_macro_bce_inflation', sa.Column('indicator_name_inflation', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('t_macro_bce_inflation', sa.Column('date_inflation', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_t_macro_bce_inflation_date', 't_macro_bce_inflation', type_='unique')
    op.create_unique_constraint(op.f('t_macro_bce_inflation_date_inflation_key'), 't_macro_bce_inflation', ['date_inflation'])
    op.drop_column('t_macro_bce_inflation', 'source_label')
    op.drop_column('t_macro_bce_inflation', 'indicator_name')
    op.drop_column('t_macro_bce_inflation', 'time_period')
    op.drop_column('t_macro_bce_inflation', 'obs_status')
    op.drop_column('t_macro_bce_inflation', 'value')
    op.drop_column('t_macro_bce_inflation', 'date')
    op.drop_column('t_macro_bce_inflation', 'id')
    
    # t_macro_bce_monetary_m3
    op.add_column('t_macro_bce_monetary_m3', sa.Column('id_monetary_m3', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('t_macro_bce_monetary_m3', sa.Column('indicator_name_m3', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('t_macro_bce_monetary_m3', sa.Column('source_label_m3', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('t_macro_bce_monetary_m3', sa.Column('monetary_m3_rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('t_macro_bce_monetary_m3', sa.Column('date_monetary_m3', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_t_macro_bce_monetary_m3_date', 't_macro_bce_monetary_m3', type_='unique')
    op.create_unique_constraint(op.f('t_macro_bce_monetary_m3_date_monetary_m3_key'), 't_macro_bce_monetary_m3', ['date_monetary_m3'])
    op.drop_column('t_macro_bce_monetary_m3', 'source_label')
    op.drop_column('t_macro_bce_monetary_m3', 'indicator_name')
    op.drop_column('t_macro_bce_monetary_m3', 'time_period')
    op.drop_column('t_macro_bce_monetary_m3', 'obs_status')
    op.drop_column('t_macro_bce_monetary_m3', 'value')
    op.drop_column('t_macro_bce_monetary_m3', 'date')
    op.drop_column('t_macro_bce_monetary_m3', 'id')
    
    # t_macro_bce_mro
    op.add_column('t_macro_bce_mro', sa.Column('id_mro', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('t_macro_bce_mro', sa.Column('time_periode_mro', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('t_macro_bce_mro', sa.Column('rate_mro', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('t_macro_bce_mro', sa.Column('indicator_name_mro', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('t_macro_bce_mro', sa.Column('source_label_mro', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('t_macro_bce_mro', sa.Column('date_mro', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_t_macro_bce_mro_date', 't_macro_bce_mro', type_='unique')
    op.create_unique_constraint(op.f('t_macro_bce_mro_date_mro_key'), 't_macro_bce_mro', ['date_mro'])
    op.drop_column('t_macro_bce_mro', 'source_label')
    op.drop_column('t_macro_bce_mro', 'indicator_name')
    op.drop_column('t_macro_bce_mro', 'time_period')
    op.drop_column('t_macro_bce_mro', 'obs_status')
    op.drop_column('t_macro_bce_mro', 'value')
    op.drop_column('t_macro_bce_mro', 'date')
    op.drop_column('t_macro_bce_mro', 'id')
    
    # t_macro_bce_unemployment
    op.add_column('t_macro_bce_unemployment', sa.Column('unemployment_rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('t_macro_bce_unemployment', sa.Column('id_unemployment', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('t_macro_bce_unemployment', sa.Column('indicator_name_unemployment', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('t_macro_bce_unemployment', sa.Column('date_unemployment', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('t_macro_bce_unemployment', sa.Column('source_label_unemployment', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint('uq_t_macro_bce_unemployment_date', 't_macro_bce_unemployment', type_='unique')
    op.create_unique_constraint(op.f('t_macro_bce_unemployment_date_unemployment_key'), 't_macro_bce_unemployment', ['date_unemployment'])
    op.drop_column('t_macro_bce_unemployment', 'source_label')
    op.drop_column('t_macro_bce_unemployment', 'indicator_name')
    op.drop_column('t_macro_bce_unemployment', 'time_period')
    op.drop_column('t_macro_bce_unemployment', 'obs_status')
    op.drop_column('t_macro_bce_unemployment', 'value')
    op.drop_column('t_macro_bce_unemployment', 'date')
    op.drop_column('t_macro_bce_unemployment', 'id')

    # 3. Recréer la vue avec les ANCIENS noms de colonnes suffixés
    op.execute("""
        CREATE VIEW v_macro_indicators_daily_v1 AS
        SELECT 
            COALESCE(mro.date_mro, inf.date_inflation, unemp.date_unemployment, m3.date_monetary_m3) AS day,
            mro.rate_mro,
            inf.inflation_rate,
            unemp.unemployment_rate,
            m3.monetary_m3_rate
        FROM t_macro_bce_mro mro
        FULL OUTER JOIN t_macro_bce_inflation inf 
            ON mro.date_mro = inf.date_inflation
        FULL OUTER JOIN t_macro_bce_unemployment unemp 
            ON COALESCE(mro.date_mro, inf.date_inflation) = unemp.date_unemployment
        FULL OUTER JOIN t_macro_bce_monetary_m3 m3 
            ON COALESCE(mro.date_mro, inf.date_inflation, unemp.date_unemployment) = m3.date_monetary_m3
        ORDER BY day
    """)
# ...existing code...