"""create all macro and btc tables

Revision ID: a35097d1ed2f
Revises: 
Create Date: 2025-06-16 16:54:07.435263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a35097d1ed2f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_bitcoin_prices',
    sa.Column('id_price_bitcoin', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_bitcoin', sa.Date(), nullable=False),
    sa.Column('time_open_bitcoin', sa.DateTime(), nullable=True),
    sa.Column('time_close_bitcoin', sa.DateTime(), nullable=True),
    sa.Column('time_high_bitcoin', sa.DateTime(), nullable=True),
    sa.Column('time_low_bitcoin', sa.DateTime(), nullable=True),
    sa.Column('open_price_bitcoin', sa.Float(), nullable=False),
    sa.Column('close_price_bitcoin', sa.Float(), nullable=False),
    sa.Column('high_price_bitcoin', sa.Float(), nullable=True),
    sa.Column('low_price_bitcoin', sa.Float(), nullable=True),
    sa.Column('volume_bitcoin', sa.Float(), nullable=True),
    sa.Column('market_Cap_bitcoin', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_price_bitcoin'),
    sa.UniqueConstraint('date_bitcoin')
    )
    op.create_table('t_macro_bce_inflation',
    sa.Column('id_inflation', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_inflation', sa.Date(), nullable=False),
    sa.Column('inflation_rate', sa.Float(), nullable=True),
    sa.Column('time_periode_inflation', sa.String(length=100), nullable=True),
    sa.Column('indicator_name_inflation', sa.String(length=100), nullable=True),
    sa.Column('source_label_inflation', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_inflation'),
    sa.UniqueConstraint('date_inflation')
    )
    op.create_table('t_macro_bce_monetary_m3',
    sa.Column('id_monetary_m3', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_monetary_m3', sa.Date(), nullable=False),
    sa.Column('monetary_m3_rate', sa.Float(), nullable=True),
    sa.Column('indicator_name_m3', sa.String(length=100), nullable=True),
    sa.Column('source_label_m3', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_monetary_m3'),
    sa.UniqueConstraint('date_monetary_m3')
    )
    op.create_table('t_macro_bce_mro',
    sa.Column('id_mro', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_mro', sa.Date(), nullable=False),
    sa.Column('rate_mro', sa.Float(), nullable=True),
    sa.Column('time_periode_mro', sa.String(length=100), nullable=True),
    sa.Column('indicator_name_mro', sa.String(length=100), nullable=True),
    sa.Column('source_label_mro', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_mro'),
    sa.UniqueConstraint('date_mro')
    )
    op.create_table('t_macro_bce_unemployment',
    sa.Column('id_unemployment', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_unemployment', sa.Date(), nullable=False),
    sa.Column('unemployment_rate', sa.Float(), nullable=True),
    sa.Column('indicator_name_unemployment', sa.String(length=100), nullable=True),
    sa.Column('source_label_unemployment', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_unemployment'),
    sa.UniqueConstraint('date_unemployment')
    )
    op.create_table('t_users',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_user', sa.String(length=50), nullable=False),
    sa.Column('email_user', sa.String(length=100), nullable=False),
    sa.Column('password_user', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_users')
    op.drop_table('t_macro_bce_unemployment')
    op.drop_table('t_macro_bce_mro')
    op.drop_table('t_macro_bce_monetary_m3')
    op.drop_table('t_macro_bce_inflation')
    op.drop_table('t_bitcoin_prices')
    # ### end Alembic commands ###
