"""refactor bitcoin prices table structure

Revision ID: c24e71c09ba3
Revises: c417baba77db
Create Date: 2026-06-02 10:56:02.856611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c24e71c09ba3'
down_revision: Union[str, None] = 'c417baba77db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('v_macro_indicators_daily_v1',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('rate_mro', sa.Float(), nullable=True),
    sa.Column('inflation_rate', sa.Float(), nullable=True),
    sa.Column('unemployment_rate', sa.Float(), nullable=True),
    sa.Column('monetary_m3_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('day')
    )
    op.add_column('t_bitcoin_prices', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('t_bitcoin_prices', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('t_bitcoin_prices', sa.Column('open', sa.Numeric(precision=18, scale=8), nullable=False))
    op.add_column('t_bitcoin_prices', sa.Column('high', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('t_bitcoin_prices', sa.Column('low', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('t_bitcoin_prices', sa.Column('close', sa.Numeric(precision=18, scale=8), nullable=False))
    op.add_column('t_bitcoin_prices', sa.Column('volume', sa.Numeric(precision=24, scale=8), nullable=True))
    op.add_column('t_bitcoin_prices', sa.Column('market_cap', sa.Numeric(precision=28, scale=8), nullable=True))
    op.add_column('t_bitcoin_prices', sa.Column('source', sa.String(length=50), nullable=False))
    op.add_column('t_bitcoin_prices', sa.Column('currency', sa.String(length=10), nullable=False))
    op.add_column('t_bitcoin_prices', sa.Column('granularity', sa.String(length=20), nullable=False))
    op.add_column('t_bitcoin_prices', sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('t_bitcoin_prices_date_bitcoin_key'), 't_bitcoin_prices', type_='unique')
    op.create_unique_constraint('uq_t_bitcoin_prices_date_source_currency_granularity', 't_bitcoin_prices', ['date', 'source', 'currency', 'granularity'])
    op.drop_column('t_bitcoin_prices', 'id_price_bitcoin')
    op.drop_column('t_bitcoin_prices', 'time_high_bitcoin')
    op.drop_column('t_bitcoin_prices', 'time_low_bitcoin')
    op.drop_column('t_bitcoin_prices', 'open_price_bitcoin')
    op.drop_column('t_bitcoin_prices', 'time_close_bitcoin')
    op.drop_column('t_bitcoin_prices', 'date_bitcoin')
    op.drop_column('t_bitcoin_prices', 'time_open_bitcoin')
    op.drop_column('t_bitcoin_prices', 'low_price_bitcoin')
    op.drop_column('t_bitcoin_prices', 'high_price_bitcoin')
    op.drop_column('t_bitcoin_prices', 'market_Cap_bitcoin')
    op.drop_column('t_bitcoin_prices', 'close_price_bitcoin')
    op.drop_column('t_bitcoin_prices', 'volume_bitcoin')
    op.add_column('t_users', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_users', 'is_active')
    op.add_column('t_bitcoin_prices', sa.Column('volume_bitcoin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('t_bitcoin_prices', sa.Column('close_price_bitcoin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('t_bitcoin_prices', sa.Column('market_Cap_bitcoin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('t_bitcoin_prices', sa.Column('high_price_bitcoin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('t_bitcoin_prices', sa.Column('low_price_bitcoin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('t_bitcoin_prices', sa.Column('time_open_bitcoin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('t_bitcoin_prices', sa.Column('date_bitcoin', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('t_bitcoin_prices', sa.Column('time_close_bitcoin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('t_bitcoin_prices', sa.Column('open_price_bitcoin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('t_bitcoin_prices', sa.Column('time_low_bitcoin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('t_bitcoin_prices', sa.Column('time_high_bitcoin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('t_bitcoin_prices', sa.Column('id_price_bitcoin', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint('uq_t_bitcoin_prices_date_source_currency_granularity', 't_bitcoin_prices', type_='unique')
    op.create_unique_constraint(op.f('t_bitcoin_prices_date_bitcoin_key'), 't_bitcoin_prices', ['date_bitcoin'], postgresql_nulls_not_distinct=False)
    op.drop_column('t_bitcoin_prices', 'collected_at')
    op.drop_column('t_bitcoin_prices', 'granularity')
    op.drop_column('t_bitcoin_prices', 'currency')
    op.drop_column('t_bitcoin_prices', 'source')
    op.drop_column('t_bitcoin_prices', 'market_cap')
    op.drop_column('t_bitcoin_prices', 'volume')
    op.drop_column('t_bitcoin_prices', 'close')
    op.drop_column('t_bitcoin_prices', 'low')
    op.drop_column('t_bitcoin_prices', 'high')
    op.drop_column('t_bitcoin_prices', 'open')
    op.drop_column('t_bitcoin_prices', 'date')
    op.drop_column('t_bitcoin_prices', 'id')
    op.drop_table('v_macro_indicators_daily_v1')
    # ### end Alembic commands ###
