"""Ajout du champ role_user dans t_users

Revision ID: c417baba77db
Revises: daa38defa7ad
Create Date: 2025-06-26 13:45:56.197167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c417baba77db'
down_revision: Union[str, None] = 'daa38defa7ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_users', sa.Column('role_user', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_users', 'role_user')
    # ### end Alembic commands ###
