"""Renommage de password_user en hashed_password_user

Revision ID: daa38defa7ad
Revises: a35097d1ed2f
Create Date: 2025-06-26 11:50:21.586441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daa38defa7ad'
down_revision: Union[str, None] = 'a35097d1ed2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_users', sa.Column('hashed_password_user', sa.String(length=100), nullable=False))
    op.drop_column('t_users', 'password_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_users', sa.Column('password_user', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('t_users', 'hashed_password_user')
    # ### end Alembic commands ###
